spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev   #开发环境
  application:
    name: microservicecloud-config-maru-dev
---
spring:
  profiles: test  #测试环境
  application:
    name: microservicecloud-config-maru-test
#请保存未utf-8形式
